logging.pattern.console:

logging.level.root: error

spring.jpa.show-sql: false
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect

logging.level.org.hibernate.SQL: error

spring.main.banner-mode: "off"